# Generated by Django 3.0.5 on 2020-05-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/uploads/docs/', verbose_name='Original File'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data/jobs_data/results/', verbose_name='Output File Zip'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data/results/results/', verbose_name='Results File'),
        ),
    ]
