# Generated by Django 3.0.5 on 2020-05-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_auto_20200529_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Job'),
        ),
    ]
