# Generated by Django 3.0.5 on 2020-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_remove_job_started_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='textObj',
        ),
        migrations.AddField(
            model_name='document',
            name='rawText',
            field=models.TextField(default='', verbose_name='Raw Test'),
        ),
        migrations.DeleteModel(
            name='DocumentText',
        ),
    ]
