# Generated by Django 3.0.5 on 2020-05-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_auto_20200530_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='production',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='rawText',
            field=models.TextField(default='', verbose_name='Raw Text'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
