# Generated by Django 3.0.5 on 2020-05-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_auto_20200531_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='supported_files',
            field=models.TextField(default='', verbose_name='Supported File Types'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='schema',
            field=models.TextField(default='', verbose_name='Job Settings'),
        ),
    ]
