# Generated by Django 3.0.5 on 2020-06-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_auto_20200531_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='production',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
