# Generated by Django 3.0.5 on 2020-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0010_auto_20200601_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='callback',
            field=models.TextField(blank=True, default='', verbose_name='Callback URL'),
        ),
    ]
