# Generated by Django 3.0.5 on 2020-06-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0011_job_callback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='schema',
            field=models.TextField(blank=True, default='', verbose_name='Job Settings'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='supported_files',
            field=models.TextField(blank=True, default='', verbose_name='Supported File Types'),
        ),
    ]
