# Generated by Django 3.0.5 on 2020-07-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0012_auto_20200628_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestep',
            name='parent_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelinesteps', to='Jobs.Pipeline'),
        ),
    ]
