# Generated by Django 3.0.5 on 2020-07-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0013_auto_20200703_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='x_coord',
            field=models.IntegerField(default=0, verbose_name='Graph X Coordinate'),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='y_coord',
            field=models.IntegerField(default=0, verbose_name='Graph Y Coordinate'),
        ),
    ]
