# Generated by Django 3.0.5 on 2020-07-22 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0015_auto_20200721_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(default='', verbose_name='Link Label')),
                ('transform_script', models.TextField(blank=True, default='', verbose_name='Data Transform Script')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('THROUGH_SCRIPT', 'Python Script'), ('ROOT_NODE', 'Root node - provides data, doc and setting.'), ('PACKAGING_NODE', 'Packaging node - instructions to package results.'), ('CALLBACK', 'Callback - send data or docs out to external API'), ('API_REQUEST', 'API Request - request data or docs from an external API')], default='THROUGH_SCRIPT', max_length=128)),
                ('name', models.CharField(default='Step Name', max_length=512)),
                ('input_transform', models.TextField(blank=True, default='', verbose_name='Input Transformation')),
                ('step_settings', models.TextField(blank=True, default='', verbose_name='Step Settings')),
                ('x_coord', models.IntegerField(default=0, verbose_name='X Coordinate')),
                ('y_coord', models.IntegerField(default=0, verbose_name='Y Coordinate')),
                ('step_number', models.IntegerField(default=-1)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelinesteps', to='Jobs.Pipeline')),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jobs.PythonScript')),
            ],
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='parent_pipeline',
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='script',
        ),
        migrations.RemoveField(
            model_name='port',
            name='node',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.AddField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edge_two', to='Jobs.PipelineNode'),
        ),
        migrations.AddField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edge_one', to='Jobs.PipelineNode'),
        ),
        migrations.AlterField(
            model_name='result',
            name='job_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.PipelineNode'),
        ),
        migrations.DeleteModel(
            name='PipelineStep',
        ),
    ]
