# Generated by Django 3.0.5 on 2020-07-22 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0016_auto_20200721_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edge',
            name='parent_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_edges', to='Jobs.Pipeline'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_edges', to='Jobs.PipelineNode'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_edges', to='Jobs.PipelineNode'),
        ),
        migrations.AlterField(
            model_name='pipelinenode',
            name='parent_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelinenodes', to='Jobs.Pipeline'),
        ),
    ]
