# Generated by Django 3.0.5 on 2020-07-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0017_auto_20200721_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='Jobs.PipelineNode'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='label',
            field=models.TextField(blank=True, default='', verbose_name='Link Label'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='parent_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_edges', to='Jobs.Pipeline'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='Jobs.PipelineNode'),
        ),
    ]
