# Generated by Django 3.0.5 on 2020-07-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0018_auto_20200726_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='root_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jobs.PipelineNode'),
        ),
    ]
