# Generated by Django 3.0.5 on 2020-08-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0019_pipeline_root_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultinputdata',
            name='owner',
        ),
        migrations.RenameField(
            model_name='pythonscript',
            old_name='required_inputs',
            new_name='schema',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='job_step',
            new_name='pipeline_node',
        ),
        migrations.RemoveField(
            model_name='result',
            name='input_data',
        ),
        migrations.AddField(
            model_name='result',
            name='raw_input_data',
            field=models.TextField(blank=True, default='', verbose_name='Raw Input Json Data'),
        ),
        migrations.AddField(
            model_name='result',
            name='transformed_input_data',
            field=models.TextField(blank=True, default='', verbose_name='Transformed Input Json Data'),
        ),
        migrations.AlterField(
            model_name='result',
            name='output_data',
            field=models.TextField(default='{}', verbose_name='Result Data'),
        ),
        migrations.DeleteModel(
            name='ResultData',
        ),
        migrations.DeleteModel(
            name='ResultInputData',
        ),
    ]
