# Generated by Django 3.0.5 on 2020-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0021_auto_20200802_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogentry',
            name='msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tasklogentry',
            name='trace',
            field=models.TextField(blank=True, default=''),
        ),
    ]
