# Generated by Django 3.0.5 on 2020-08-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0022_auto_20200802_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Pipeline Description'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(default='Line Name', max_length=512, verbose_name='Pipeline Name'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='production',
            field=models.BooleanField(blank=True, default=False, verbose_name='Available in Production'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='schema',
            field=models.TextField(blank=True, default='', verbose_name='Pipeline Schema'),
        ),
    ]
