# Generated by Django 3.0.5 on 2020-08-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0023_auto_20200802_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='input_settings',
            field=models.TextField(blank=True, default='{}', verbose_name='Input Settings'),
        ),
        migrations.AlterField(
            model_name='result',
            name='output_data',
            field=models.TextField(default='{}', verbose_name='Result Data'),
        ),
        migrations.AlterField(
            model_name='result',
            name='raw_input_data',
            field=models.TextField(blank=True, default='{}', verbose_name='Raw Input Json Data'),
        ),
        migrations.AlterField(
            model_name='result',
            name='transformed_input_data',
            field=models.TextField(blank=True, default='{}', verbose_name='Transformed Input Json Data'),
        ),
    ]
