# Generated by Django 3.0.5 on 2020-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0024_auto_20200809_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='scale',
            field=models.FloatField(default=1.0, verbose_name='View Scale Factor'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='x_offset',
            field=models.IntegerField(default=0, verbose_name='X Offset'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='y_offset',
            field=models.IntegerField(default=0, verbose_name='Y Offset'),
        ),
    ]
