# Generated by Django 3.0.5 on 2020-08-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0028_auto_20200815_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Step Start Date and Time'),
        ),
        migrations.AddField(
            model_name='job',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Step Stop Date and Time'),
        ),
    ]
