# Generated by Django 3.1.1 on 2020-09-06 19:12

import Jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0029_auto_20200816_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='digraph',
            field=models.JSONField(default=Jobs.models.digraph_jsonfield_default_value),
        ),
    ]
