# Generated by Django 3.1.1 on 2020-09-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0030_pipeline_digraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='locked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Object locked (backend performing updates)...'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='locked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Object locked (backend performing updates)...'),
        ),
        migrations.AddField(
            model_name='pipelinenode',
            name='locked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Object locked (backend performing updates)...'),
        ),
        migrations.AddField(
            model_name='pythonscript',
            name='locked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Object locked (backend performing updates)...'),
        ),
    ]
