# Generated by Django 3.1.1 on 2020-10-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0032_job_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='install_error',
            field=models.BooleanField(blank=True, default=False, verbose_name='Object locked (backend performing updates)...'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='install_error_code',
            field=models.TextField(blank=True, default='', verbose_name='Error Description'),
        ),
        migrations.AddField(
            model_name='pythonscript',
            name='install_error',
            field=models.BooleanField(blank=True, default=False, verbose_name='Object locked (backend performing updates)...'),
        ),
        migrations.AddField(
            model_name='pythonscript',
            name='install_error_code',
            field=models.TextField(blank=True, default='', verbose_name='Error Description'),
        ),
    ]
