# Generated by Django 3.1.1 on 2020-10-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0033_auto_20201018_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonscript',
            name='env_variables_need_install',
            field=models.BooleanField(blank=True, default=False, verbose_name='Env Variables Install Needed'),
        ),
        migrations.AddField(
            model_name='pythonscript',
            name='package_needs_install',
            field=models.BooleanField(blank=True, default=False, verbose_name='Package Install Needed'),
        ),
        migrations.AddField(
            model_name='pythonscript',
            name='script_needs_install',
            field=models.BooleanField(blank=True, default=False, verbose_name='Script Install Needed'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='install_error',
            field=models.BooleanField(blank=True, default=False, verbose_name='Installation Error'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='install_error_code',
            field=models.TextField(blank=True, default='', verbose_name='Installation Error Description'),
        ),
        migrations.AlterField(
            model_name='pythonscript',
            name='install_error',
            field=models.BooleanField(blank=True, default=False, verbose_name='Installation Error'),
        ),
        migrations.AlterField(
            model_name='pythonscript',
            name='install_error_code',
            field=models.TextField(blank=True, default='', verbose_name='Installation Error Description'),
        ),
    ]
