# Generated by Django 3.1.1 on 2020-10-21 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0034_auto_20201020_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonscript',
            name='locked',
        ),
    ]
