# Generated by Django 3.1.1 on 2020-10-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0035_remove_pythonscript_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonscript',
            name='locked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Locked by backend.'),
        ),
    ]
