# Generated by Django 3.1.1 on 2020-10-28 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0036_pythonscript_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='job',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pythonscript',
            name='install_error_code',
            field=models.TextField(default='', verbose_name='Installation Error Description'),
        ),
    ]
