# Generated by Django 3.1.1 on 2020-11-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0037_auto_20201027_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created',
        ),
        migrations.AlterField(
            model_name='edge',
            name='parent_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='Jobs.pipeline'),
        ),
        migrations.AlterField(
            model_name='pipelinenode',
            name='parent_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='Jobs.pipeline'),
        ),
    ]
