# Generated by Django 3.1.1 on 2020-11-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0038_auto_20201102_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_edges', to='Jobs.pipelinenode'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_edges', to='Jobs.pipelinenode'),
        ),
    ]
