# Generated by Django 3.1.1 on 2020-11-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0040_auto_20201106_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='Jobs.pipelinenode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='Jobs.pipelinenode'),
            preserve_default=False,
        ),
    ]
