# Generated by Django 3.1.1 on 2020-11-19 19:44

import Jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0044_auto_20201119_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='start_state',
            field=models.JSONField(default=Jobs.models.blank_json),
        ),
    ]
