# Generated by Django 3.1.1 on 2020-11-22 22:07

import Jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0045_auto_20201119_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='json_schema',
            field=models.JSONField(default=Jobs.models.blank_json),
        ),
        migrations.AddField(
            model_name='pythonscript',
            name='json_schema',
            field=models.JSONField(default=Jobs.models.blank_json),
        ),
        migrations.AlterField(
            model_name='result',
            name='start_state',
            field=models.JSONField(default=Jobs.models.blank_state),
        ),
    ]
