# Generated by Django 3.1.1 on 2020-12-13 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0046_auto_20201122_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptDataFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='data/data_files/', verbose_name='Script Data File')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Job Creation Date and Time')),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='pythonscript',
            name='data_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jobs.scriptdatafile'),
        ),
    ]
