# Generated by Django 3.1.1 on 2020-12-17 02:23

import Jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0048_auto_20201214_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptdatafile',
            name='zip_contents',
            field=models.TextField(blank=True, default='', verbose_name='File contents'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='json_schema',
            field=Jobs.models.GremlinJSONField(default=Jobs.models.blank_json),
        ),
        migrations.AlterField(
            model_name='pythonscript',
            name='json_schema',
            field=Jobs.models.GremlinJSONField(default=Jobs.models.blank_json),
        ),
        migrations.AlterField(
            model_name='result',
            name='end_state',
            field=Jobs.models.GremlinJSONField(default=Jobs.models.blank_state),
        ),
        migrations.AlterField(
            model_name='result',
            name='job_inputs',
            field=Jobs.models.GremlinJSONField(default=Jobs.models.blank_json),
        ),
        migrations.AlterField(
            model_name='result',
            name='node_inputs',
            field=Jobs.models.GremlinJSONField(default=Jobs.models.blank_json),
        ),
        migrations.AlterField(
            model_name='result',
            name='node_output_data',
            field=Jobs.models.GremlinJSONField(default=Jobs.models.blank_json),
        ),
        migrations.AlterField(
            model_name='result',
            name='start_state',
            field=Jobs.models.GremlinJSONField(default=Jobs.models.blank_state),
        ),
    ]
