# Generated by Django 3.1.1 on 2020-12-18 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0049_auto_20201216_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='creation_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='scriptdatafile',
            old_name='creation_time',
            new_name='created',
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOTIFICATION', 'Notice from system.'), ('SCRIPT_EXPORT', 'Export script to zip file.'), ('SCRIPT_IMPORT', 'Import script from zip file.'), ('PIPELINE_EXPORT', 'Export pipeline to zip file.'), ('PIPELINE_IMPORT', 'Import pipeline from zip file.')], default='NOTIFICATION', max_length=128)),
                ('message', models.TextField(default='', verbose_name='Message')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='data/data_files/', verbose_name='Notification Data')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Job Creation Date and Time')),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
