# Generated by Django 3.1.1 on 2020-12-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0051_auto_20201219_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonscript',
            name='data_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jobs.scriptdatafile'),
        ),
    ]
