# Generated by Django 3.1.1 on 2021-01-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0052_auto_20201220_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data/results/', verbose_name='Results File'),
        ),
    ]
