# Generated by Django 3.0.5 on 2020-05-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_pythonscript_env_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='document',
            name='results',
        ),
        migrations.AddField(
            model_name='document',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Job'),
            preserve_default=False,
        ),
    ]
