version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  worker_usr_data: {}
  worker_tmp: {}

services:
  gremlin: &gremlin
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: gremlin_gplv3_local_django
    container_name: gremlin
    depends_on:
      - postgres
      - tika
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gremlin_gplv3_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0
    container_name: redis

  gremlinworker:
    <<: *gremlin
    image: gremlin_gplv3_local_celeryworker
    container_name: gremlinworker
    depends_on:
      - redis
      - postgres
    volumes:
      - worker_usr_data:/usr/local
      - worker_tmp:/tmp
      - .:/app

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *gremlin
    image: gremlin_gplv3_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  flower:
    <<: *gremlin
    image: gremlin_gplv3_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower

  tika:
    image: apache/tika:1.24.1
    container_name: tika
    ports:
      - 9998:9998

  sftp:
    image: atmoz/sftp
    volumes:
        - /host/files:/home/foo/files
    ports:
        - "2222:22"
    command: foo:pass:1001
