# Generated by Django 3.0.5 on 2020-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LAWYER', 'Lawyer'), ('LEGAL_ENG', 'Legal Engineer'), ('ADMIN', 'All Privileges (Dangerous!)')], default='LAWYER', max_length=24),
        ),
    ]
