# Generated by Django 3.1.1 on 2021-04-22 02:57

from django.db import migrations
import gremlin.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_input_json',
            field=gremlin.jobs.models.GremlinJSONField(default=gremlin.jobs.models.blank_json),
        ),
    ]
