# Generated by Django 3.1.1 on 2021-04-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_input_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_inputs',
        ),
    ]
