# Generated by Django 3.1.1 on 2020-10-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201008_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VIEWONLY', 'View Only'), ('LAWYER', 'Lawyer'), ('LEGAL_ENG', 'Legal Engineer'), ('ADMIN', 'All Privileges (Dangerous!)')], default='LAWYER', max_length=24),
        ),
    ]
